language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
addons:
  sonarcloud:
    organization: "viktorc-github"
    token:
      secure: ${SONAR_TOKEN}
script:
  - python setup.py build install
  - flake8 osml
  - travis_wait 90 coverage run --source=osml setup.py test
  - coverage xml -o coverage.xml
  - sonar-scanner